# Generated by Django 3.1.5 on 2021-01-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210128_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bucket',
            field=models.CharField(default='1304853137', max_length=127),
        ),
    ]
